export const PROJECT_DATA = [
  {
    position: "right",
    link: "https://raw.githubusercontent.com/Tusharborul/temp/main/parking_website.png",
    title: "Mart Ecommerce-Website",
    date: "🚗",
    desc: "SOLID principles with Spring Data JPA. Razorpay payments & refunds, JWT auth, dashboards for account & parking management, user reviews.",
    tags: ["react.js", "springboot", "Asp.net", "JWT Token", "java", "c#", "bootstrap"],
    live: "https://github.com/Tusharborul/Online-Car-Parking-Application.git",
    github: "https://github.com/Tusharborul/Online-Car-Parking-Application.git",
  },
  {
    position: "left",
    link: "https://raw.githubusercontent.com/Tusharborul/temp/main/Mart.png",
    title: "Mart Ecommerce-Website",
    date: "📲",
    desc: "Crafted a dynamic e-commerce site using HTML, CSS, and JS. Achieved seamless navigation, responsive design, and interactive features for an elegant and functional online shopping experience.",
    tags: ["Html", "CSS3", "JavaScript"],
    live: "https://tusharborul.github.io/Ecommerce-Website/",
    github: "https://github.com/Tusharborul/Ecommerce-Website.git",
  },
  {
    position: "right",
    link: "https://raw.githubusercontent.com/Tusharborul/temp/main/coffee-shop.png",
    title: "Coffee-Shop",
    date: " ☕",
    desc: "Built a lively coffee shop website using HTML, CSS, and JS. Featuring a user-friendly design, responsive layout, and interactive elements for a delightful online experience.",
    tags: ["Html", "CSS3", "JavaScript"],
    live: "https://tusharborul.github.io/Coffee-Shop/",
    github: "https://github.com/Tusharborul/Coffee-Shop.git",
  },
  {
    position: "left",
    link: "https://raw.githubusercontent.com/Tusharborul/temp/main/To-Do-List.png",
    title: "To-DO App",
    date: "(FEBRUARY 2023) 📲",
    desc: "My to-do app, designed with pure HTML, CSS, and JS, offers full CRUD functionality and responsive design for seamless task management.",
    tags: ["Html", "CSS3", "JavaScript"],
    live: "https://tusharborul.github.io/To-Do-List/",
    github: "https://github.com/Tusharborul/To-Do-List.git",
  },
  {
    position: "right",
    link: "https://raw.githubusercontent.com/Tusharborul/temp/main/2048.png",
    title: "2048 Game",
    date: "🎮",
    desc: "Designed and implemented a captivating 2048 game website with HTML, CSS, and JS. Delivered seamless gameplay, sleek visuals, and an engaging user interface for an immersive gaming experience.",
    tags: ["Html", "CSS3", "JavaScript"],
    live: "https://tusharborul.github.io/2048-Game/",
    github: "https://github.com/Tusharborul/2048-Game.git",
  },
  {
    position: "left",
    link: "https://raw.githubusercontent.com/Tusharborul/temp/main/tic-tac-toe.png",
    title: "Tic Tac Toe Game",
    date: "🎮",
    desc: "Designed and coded a Tic-Tac-Toe game website using HTML, CSS, and JS. Implemented sleek visuals and responsive functionality for an immersive gaming experience, symbolizing strategic fun.",
    tags: ["Html", "CSS3", "JavaScript"],
    live: "https://tusharborul.github.io/tic-tac-toe/",
    github: "https://github.com/Tusharborul/tic-tac-toe.git",
  },
];